services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    container_name: explorify_frontend
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local
    volumes:
      - "./frontend:/app"
    ports:
      - 3000:3000

  backend:
    build: ./backend
    restart: unless-stopped
    container_name: explorify_webserver
    depends_on:
      - rabbitmq
    ports:
      - 3001:3001
    env_file:
      - .env.global

  playlist_processor:
    build: ./processor
    restart: unless-stopped
    depends_on:
      - rabbitmq
    ports:
      - 3002
    env_file:
      - .env.global

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    env_file:
      - .env.global
