services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    container_name: ${EXPLORIFY_CLIENT_NAME}
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - "./frontend:/app"
    ports:
      - ${EXPLORIFY_CLIENT_PORT}:3000

  backend:
    build: ./backend
    restart: unless-stopped
    container_name: ${EXPLORIFY_WEBSERVER_NAME}
    depends_on:
      - rabbitmq
    ports:
      - ${EXPLORIFY_WEBSERVER_PORT}:3001
    env_file:
      - .env

  playlist_processor:
    build: ./processor
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - ${EXPLORIFY_PROCESSOR_PORT}
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    container_name: ${RABBITMQ_SERVER_NAME}
    depends_on:
      - mysql
    ports:
      - ${RABBITMQ_SERVER_PORT0}:5672
      - ${RABBITMQ_SERVER_PORT1}:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    env_file:
      - .env

  mysql:
    build:
      context: ./database/
    image: "mysql:8.0"
    container_name: ${MYSQL_HOST_NAME}
    restart: unless-stopped
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ./database/data:/var/lib/mysql
    env_file:
      - .env
